<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/12 18:57:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mysql1.mijnhostingpartner.nl;dbname=Baarsma_letsonline',
  'username' => 'Baarsma_lets',
  'password' => 'dUH@#s82KK',
  'attributes' => 
  array (
    'tblname_format' => 'lets_%s',
  ),
  'name' => 'doctrine',
)),);
