<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/14 16:34:04
$this->security = array (
  'edit' => 
  array (
    'credentials' => 'manage_users',
  ),
  'delete' => 
  array (
    'credentials' => 'manage_users',
  ),
  'new' => 
  array (
    'credentials' => 'manage_users',
  ),
  'create' => 
  array (
    'credentials' => 'manage_users',
  ),
  'activate' => 
  array (
    'credentials' => 'manage_users',
  ),
  'deactivate' => 
  array (
    'credentials' => 'manage_users',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'view_users',
  ),
);
