<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/12/12 18:57:10
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'dologin' => 
  array (
    'is_secure' => false,
  ),
  'forgot_password' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
