<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/05/02 06:35:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mysql6.mijnhostingpartner.nl;dbname=Baarsma_letsonline',
  'username' => 'Baarsma_lets',
  'password' => 'dUH@#s82KK',
  'attributes' => 
  array (
    'tblname_format' => 'lets_%s',
  ),
  'name' => 'doctrine',
)),);
