<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/02 06:35:51
sfConfig::add(array(
  'app_password_secret' => '$ecr==t12n1124d@@f',
  'app_avatar_size' => '68x90',
  'app_paging_limit' => 10,
  'app_accept_languages' => array (
  0 => 'nl',
  1 => 'en',
),
  'app_user_credentials' => array (
  'manage_users' => 'Manage Users',
  'view_users' => 'View Users',
),
  'app_offer_experiences' => array (
  'n/a' => 'N/A',
  'hobby' => 'Hobby',
  'trained' => 'Trained',
  'prof' => 'Professional',
),
  'app_offer_types' => array (
  'request' => 'Request',
  'offer' => 'Offer',
),
));
