<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/05/02 06:35:54
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'dologin' => 
  array (
    'is_secure' => false,
  ),
  'forgot_password' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
