<?php

/**
 * BaseOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $user_id
 * @property integer $category_id
 * @property string $type
 * @property string $description
 * @property string $experience
 * @property User $User
 * @property Category $Category
 * 
 * @method integer  getProjectId()   Returns the current record's "project_id" value
 * @method integer  getUserId()      Returns the current record's "user_id" value
 * @method integer  getCategoryId()  Returns the current record's "category_id" value
 * @method string   getType()        Returns the current record's "type" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method string   getExperience()  Returns the current record's "experience" value
 * @method User     getUser()        Returns the current record's "User" value
 * @method Category getCategory()    Returns the current record's "Category" value
 * @method Offer    setProjectId()   Sets the current record's "project_id" value
 * @method Offer    setUserId()      Sets the current record's "user_id" value
 * @method Offer    setCategoryId()  Sets the current record's "category_id" value
 * @method Offer    setType()        Sets the current record's "type" value
 * @method Offer    setDescription() Sets the current record's "description" value
 * @method Offer    setExperience()  Sets the current record's "experience" value
 * @method Offer    setUser()        Sets the current record's "User" value
 * @method Offer    setCategory()    Sets the current record's "Category" value
 * 
 * @package    letsonline
 * @subpackage model
 * @author     Rein Baarsma <solidwebcode@googlemail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOffer extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('offer');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('experience', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->index('user_index', array(
             'fields' => 
             array(
              0 => 'project_id',
              1 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}