<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $project_id
 * @property Offer $Offers
 * 
 * @method string   getName()       Returns the current record's "name" value
 * @method integer  getProjectId()  Returns the current record's "project_id" value
 * @method Offer    getOffers()     Returns the current record's "Offers" value
 * @method Category setName()       Sets the current record's "name" value
 * @method Category setProjectId()  Sets the current record's "project_id" value
 * @method Category setOffers()     Sets the current record's "Offers" value
 * 
 * @package    letsonline
 * @subpackage model
 * @author     Rein Baarsma <solidwebcode@googlemail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Offer as Offers', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}