<?php

/**
 * BaseCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $sender_id
 * @property integer $receiver_id
 * @property float $amount
 * @property datetime $date
 * @property string $description
 * @property boolean $confirmed
 * @property User $Receiver
 * @property User $Sender
 * 
 * @method integer  getProjectId()   Returns the current record's "project_id" value
 * @method integer  getSenderId()    Returns the current record's "sender_id" value
 * @method integer  getReceiverId()  Returns the current record's "receiver_id" value
 * @method float    getAmount()      Returns the current record's "amount" value
 * @method datetime getDate()        Returns the current record's "date" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method boolean  getConfirmed()   Returns the current record's "confirmed" value
 * @method User     getReceiver()    Returns the current record's "Receiver" value
 * @method User     getSender()      Returns the current record's "Sender" value
 * @method Coupon   setProjectId()   Sets the current record's "project_id" value
 * @method Coupon   setSenderId()    Sets the current record's "sender_id" value
 * @method Coupon   setReceiverId()  Sets the current record's "receiver_id" value
 * @method Coupon   setAmount()      Sets the current record's "amount" value
 * @method Coupon   setDate()        Sets the current record's "date" value
 * @method Coupon   setDescription() Sets the current record's "description" value
 * @method Coupon   setConfirmed()   Sets the current record's "confirmed" value
 * @method Coupon   setReceiver()    Sets the current record's "Receiver" value
 * @method Coupon   setSender()      Sets the current record's "Sender" value
 * 
 * @package    letsonline
 * @subpackage model
 * @author     Rein Baarsma <solidwebcode@googlemail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCoupon extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sender_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('receiver_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('confirmed', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('receiver_index', array(
             'fields' => 
             array(
              0 => 'project_id',
              1 => 'receiver_id',
              2 => 'confirmed',
             ),
             ));
        $this->index('sender_index', array(
             'fields' => 
             array(
              0 => 'project_id',
              1 => 'sender_id',
              2 => 'confirmed',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as Receiver', array(
             'local' => 'receiver_id',
             'foreign' => 'id'));

        $this->hasOne('User as Sender', array(
             'local' => 'sender_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}