<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $no
 * @property string $login
 * @property string $language
 * @property string $session
 * @property array $credentials
 * @property integer $user_level
 * @property string $password
 * @property string $email
 * @property string $display_name
 * @property string $first_name
 * @property string $last_name
 * @property string $address_line
 * @property string $zip_code
 * @property string $city
 * @property string $country
 * @property string $phone_home
 * @property string $phone_mobile
 * @property string $phone_work
 * @property date $birth_date
 * @property string $personal_text
 * @property string $avatar
 * @property boolean $show_email
 * @property boolean $show_phone
 * @property boolean $show_address
 * @property boolean $show_age
 * @property integer $logins
 * @property datetime $last_login
 * @property float $old_lets
 * @property float $total_payed
 * @property float $total_received
 * @property boolean $deleted
 * @property datetime $deleted_on
 * @property Project $Project
 * @property Offer $Offers
 * @property Coupon $SentCoupons
 * @property Coupon $ReceivedCoupons
 * @property Doctrine_Collection $Message
 * 
 * @method integer             getProjectId()       Returns the current record's "project_id" value
 * @method integer             getNo()              Returns the current record's "no" value
 * @method string              getLogin()           Returns the current record's "login" value
 * @method string              getLanguage()        Returns the current record's "language" value
 * @method string              getSession()         Returns the current record's "session" value
 * @method array               getCredentials()     Returns the current record's "credentials" value
 * @method integer             getUserLevel()       Returns the current record's "user_level" value
 * @method string              getPassword()        Returns the current record's "password" value
 * @method string              getEmail()           Returns the current record's "email" value
 * @method string              getDisplayName()     Returns the current record's "display_name" value
 * @method string              getFirstName()       Returns the current record's "first_name" value
 * @method string              getLastName()        Returns the current record's "last_name" value
 * @method string              getAddressLine()     Returns the current record's "address_line" value
 * @method string              getZipCode()         Returns the current record's "zip_code" value
 * @method string              getCity()            Returns the current record's "city" value
 * @method string              getCountry()         Returns the current record's "country" value
 * @method string              getPhoneHome()       Returns the current record's "phone_home" value
 * @method string              getPhoneMobile()     Returns the current record's "phone_mobile" value
 * @method string              getPhoneWork()       Returns the current record's "phone_work" value
 * @method date                getBirthDate()       Returns the current record's "birth_date" value
 * @method string              getPersonalText()    Returns the current record's "personal_text" value
 * @method string              getAvatar()          Returns the current record's "avatar" value
 * @method boolean             getShowEmail()       Returns the current record's "show_email" value
 * @method boolean             getShowPhone()       Returns the current record's "show_phone" value
 * @method boolean             getShowAddress()     Returns the current record's "show_address" value
 * @method boolean             getShowAge()         Returns the current record's "show_age" value
 * @method integer             getLogins()          Returns the current record's "logins" value
 * @method datetime            getLastLogin()       Returns the current record's "last_login" value
 * @method float               getOldLets()         Returns the current record's "old_lets" value
 * @method float               getTotalPayed()      Returns the current record's "total_payed" value
 * @method float               getTotalReceived()   Returns the current record's "total_received" value
 * @method boolean             getDeleted()         Returns the current record's "deleted" value
 * @method datetime            getDeletedOn()       Returns the current record's "deleted_on" value
 * @method Project             getProject()         Returns the current record's "Project" value
 * @method Offer               getOffers()          Returns the current record's "Offers" value
 * @method Coupon              getSentCoupons()     Returns the current record's "SentCoupons" value
 * @method Coupon              getReceivedCoupons() Returns the current record's "ReceivedCoupons" value
 * @method Doctrine_Collection getMessage()         Returns the current record's "Message" collection
 * @method User                setProjectId()       Sets the current record's "project_id" value
 * @method User                setNo()              Sets the current record's "no" value
 * @method User                setLogin()           Sets the current record's "login" value
 * @method User                setLanguage()        Sets the current record's "language" value
 * @method User                setSession()         Sets the current record's "session" value
 * @method User                setCredentials()     Sets the current record's "credentials" value
 * @method User                setUserLevel()       Sets the current record's "user_level" value
 * @method User                setPassword()        Sets the current record's "password" value
 * @method User                setEmail()           Sets the current record's "email" value
 * @method User                setDisplayName()     Sets the current record's "display_name" value
 * @method User                setFirstName()       Sets the current record's "first_name" value
 * @method User                setLastName()        Sets the current record's "last_name" value
 * @method User                setAddressLine()     Sets the current record's "address_line" value
 * @method User                setZipCode()         Sets the current record's "zip_code" value
 * @method User                setCity()            Sets the current record's "city" value
 * @method User                setCountry()         Sets the current record's "country" value
 * @method User                setPhoneHome()       Sets the current record's "phone_home" value
 * @method User                setPhoneMobile()     Sets the current record's "phone_mobile" value
 * @method User                setPhoneWork()       Sets the current record's "phone_work" value
 * @method User                setBirthDate()       Sets the current record's "birth_date" value
 * @method User                setPersonalText()    Sets the current record's "personal_text" value
 * @method User                setAvatar()          Sets the current record's "avatar" value
 * @method User                setShowEmail()       Sets the current record's "show_email" value
 * @method User                setShowPhone()       Sets the current record's "show_phone" value
 * @method User                setShowAddress()     Sets the current record's "show_address" value
 * @method User                setShowAge()         Sets the current record's "show_age" value
 * @method User                setLogins()          Sets the current record's "logins" value
 * @method User                setLastLogin()       Sets the current record's "last_login" value
 * @method User                setOldLets()         Sets the current record's "old_lets" value
 * @method User                setTotalPayed()      Sets the current record's "total_payed" value
 * @method User                setTotalReceived()   Sets the current record's "total_received" value
 * @method User                setDeleted()         Sets the current record's "deleted" value
 * @method User                setDeletedOn()       Sets the current record's "deleted_on" value
 * @method User                setProject()         Sets the current record's "Project" value
 * @method User                setOffers()          Sets the current record's "Offers" value
 * @method User                setSentCoupons()     Sets the current record's "SentCoupons" value
 * @method User                setReceivedCoupons() Sets the current record's "ReceivedCoupons" value
 * @method User                setMessage()         Sets the current record's "Message" collection
 * 
 * @package    letsonline
 * @subpackage model
 * @author     Rein Baarsma <solidwebcode@googlemail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('no', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('login', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('language', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('session', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('credentials', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('user_level', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_line', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('zip_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_home', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_mobile', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_work', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('birth_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('personal_text', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('avatar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('show_email', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));
        $this->hasColumn('show_phone', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));
        $this->hasColumn('show_address', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('show_age', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('logins', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('last_login', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('old_lets', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('total_payed', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('total_received', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('deleted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('deleted_on', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('display_name', array(
             'fields' => 
             array(
              0 => 'project_id',
              1 => 'display_name',
             ),
             'type' => 'unique',
             ));
        $this->index('no', array(
             'fields' => 
             array(
              0 => 'project_id',
              1 => 'no',
             ),
             'type' => 'unique',
             ));
        $this->index('project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->index('deleted_index', array(
             'fields' => 
             array(
              0 => 'project_id',
              1 => 'deleted',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id'));

        $this->hasOne('Offer as Offers', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('Coupon as SentCoupons', array(
             'local' => 'id',
             'foreign' => 'sender_id'));

        $this->hasOne('Coupon as ReceivedCoupons', array(
             'local' => 'id',
             'foreign' => 'receiver_id'));

        $this->hasMany('Message', array(
             'local' => 'id',
             'foreign' => 'receiver_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'display_name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}