<?php

/**
 * BaseProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $currency_name
 * @property string $city
 * @property string $country
 * @property string $language
 * @property Doctrine_Collection $User
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getEmail()         Returns the current record's "email" value
 * @method string              getCurrencyName()  Returns the current record's "currency_name" value
 * @method string              getCity()          Returns the current record's "city" value
 * @method string              getCountry()       Returns the current record's "country" value
 * @method string              getLanguage()      Returns the current record's "language" value
 * @method Doctrine_Collection getUser()          Returns the current record's "User" collection
 * @method Project             setName()          Sets the current record's "name" value
 * @method Project             setEmail()         Sets the current record's "email" value
 * @method Project             setCurrencyName()  Sets the current record's "currency_name" value
 * @method Project             setCity()          Sets the current record's "city" value
 * @method Project             setCountry()       Sets the current record's "country" value
 * @method Project             setLanguage()      Sets the current record's "language" value
 * @method Project             setUser()          Sets the current record's "User" collection
 * 
 * @package    letsonline
 * @subpackage model
 * @author     Rein Baarsma <solidwebcode@googlemail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProject extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('currency_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('language', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'project_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}