<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/12/31 19:23:18
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'dologin' => 
  array (
    'is_secure' => false,
  ),
  'forgot_password' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
