<?php

/**
 * MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object MessageTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Message');
  }

  public function createMessage($project_id, $sender_id, $receiver_id, $subject, $message, $date=null)
  {
    if ($project_id == 0)
      throw new Exception('createMessage should never accept empty project_id');

    $message = new Message();
    $message->setProjectId($project_id);
    $message->setSenderId($sender_id);
    $message->setReceiverId($receiver_id);
    $message->setSubject($subject);
    $message->setDate(is_null($date) ? date("Y-m-d H:i:s") : $date);
    $message->setMessage($message);
    $message->save();
  }
}