# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  avatar_size:  68x90
  paging_limit: 10
  .arrays:
    accept_languages:     [nl,en]
    user_credentials:
      manage_users: Manage Users
      view_users: View Users
    offer_experiences:
      n/a: N/A
      hobby: Hobby
      trained: Trained
      prof: Professional
    offer_types:
      request: Request
      offer: Offer
